name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: KollerSystems
          config_timezone: Europe/Budapest
          optimize: svg
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
          base_indepth: yes
          base_hireable: yes
          plugin_activity: yes
          plugin_activity_limit: 4
          plugin_achievements: yes
          plugin_achievements_limit: 3
          plugin_repositories: yes
          plugin_repositories_pinned: 6
          plugin_people: yes
          plugin_people_types: members, sponsors, thanks
          plugin_people_thanks: patrikradvanyi, vtamas1990
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_habits: yes
          plugin_habits_skipped: Koller-Database
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_ignored: SQL
          plugin_languages_indepth: no
          
